import Head from "next/head";
import { Container } from "@chakra-ui/react";
import { useRouter } from "next/router";
import Login from "./components/login";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>RoK OL Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={"full"}>
        <Login />
      </Container>
    </>
  );
}
